# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 1.9

Style/Encoding:
  EnforcedStyle: never

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 200
