#postgres: &postgres
  
#test:
 # <<: *postgres
  #database: <%= ENV['DB_NAME'] %>_test<%= ENV['TEST_ENV_NUMBER'] %>

development:
  adapter: postgresql
  encoding: utf8
  Port: 5432
  host: ec2-54-83-202-115.compute-1.amazonaws.com
  username: bxhykjwadpttjk
  password: jcug-HMCuLfdjuKtUt6WH94EX_
  database: d8oi539fehu269

#production:
#  <<: *postgres
#  pool: 25
